"""Added Auditing table

Revision ID: 16684f1835f5
Revises: 9cfc040897d2
Create Date: 2019-11-24 14:29:49.158607

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '16684f1835f5'
down_revision = '9cfc040897d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditing',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_auditing_created_date'), 'auditing', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditing_created_date'), table_name='auditing')
    op.drop_table('auditing')
    # ### end Alembic commands ###
